---
title: "bootcamp"
author: "Lindsay Berry"
date: "8/19/2015"
output: html_document
---

```{r}
library(curl)      # for reading data from https
library(dplyr)
library(ggplot2)
```

Load the data: 

```{r}
gap <- read.csv(curl("http://bit.ly/gap_data"))
head(gap)
```

## Exercise 1: 

Subset for EU and 1952, and plot: 

```{r}
eu_52 <- gap %>%
  filter(continent == "Europe", year == 1952)
ggplot(data = eu_52, aes(x = gdpPercap, y = lifeExp)) + geom_point()
```

## Exercise 2: 

```{r}
eu_5267 <- gap %>%
  filter(continent == "Europe", year %in% c(1952, 1967))
ggplot(data = eu_5267, aes(x = gdpPercap, y = lifeExp, color = factor(year))) + geom_point()
```

## Exercise 3: 

Get the new dataset:

```{r}
gap_upd <- read.csv(curl("http://bit.ly/gap_data_upd"))
```

```{r}
eu_52 <- gap_upd %>%
  filter(continent == "Europe", year == 1952)
ggplot(data = eu_52, aes(x = gdpPercap, y = lifeExp)) + geom_point()
```

```{r}
eu_5267 <- gap_upd %>%
  filter(continent == "Europe", year %in% c(1952, 1967))
ggplot(data = eu_5267, aes(x = gdpPercap, y = lifeExp, color = factor(year))) + geom_point()
```
